### ISSUE TITLE
[question] Information about how to run a aventus node

### ISSUE THREAD

**Issue by erik78se** [Aventus-Network-Services/avn-parachain#130]
Is there some information on how to run a RPC/Aventus node from the repo?

I'd be happy to try to start one up.

**Comment by dr-ngubo** [comment]
Hi, we're still in the process of rolling out our codebase as open-source so there currently isn't documentation on how to run a node from the repo but you can keep monitoring the repo.

**Comment by abbaahmad** [comment]
Hi @dr-ngubo. Any progress on this issue?
